VFB-167: Display additional fields in the users table on the admins page
NorwoodAndBrixtonFoodbank/nbf-website pull request #246
Opened 2024-04-09 10:52 UTC by minalui

## What's changed
- Display additional user profile information: First name, last name, telephone number, user role
- Allow filtering and sorting

## Screenshots / Videos
| Before     | After      |
|------------|------------|
| ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/706e4a09-442a-4330-ba75-f1646c8ec68b) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/160640328/bb20fa8a-3c73-44db-a690-694b3d31408f) |

## Checklist
- [x] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [x] I have documented the testing steps for QA
- [x] I have self-reviewed this PR
- [x] Make sure you've verified it works via `npm run dev`
- [x] Make sure you've verified it works via `npm run build` and `npm run start`
- [x] Make sure you've fixed all linting problems with `npm run lint_fix`
- [x] Make sure you've tested via `npm run test:e2e`

If you have made any changes to the database...
  - [x] The migration files are up-to-date with my final set up (`npx supabase db diff -f <name_of_migration>` should create nothing at this point)
  - [x] I have updated the typescript definitions for the database with `db:local:generate_types`
  - [N/A] I have modified the seed in `supabase/seed/seed.mts` if appropriate 
  - [x] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed` 
  - [x] With my final set up, I can run `npm run dev:reset_supabase` without any errors.
  - Does this require resetting the deployed database? - YES (remove as appropriate)
  - [x] I have checked that migration can happen successfully without resetting the database, doing the following.
    - Make sure you have rebased your branch onto dev or merged dev into your branch.
    - Checkout the dev branch
    - Run `npm run post_checkout` to reset the database, including the seed data.
    - Checkout your branch
    - Run `npx supabase migrations up --include-all --local` to run all outstanding migration files
    - Check that the resulting database is what you expect.

2024-04-09 10:56 UTC, minalui commented on src/app/admin/usersTable/getUsersData.ts
> +        query = query.order("first_name");
Should we order by first name or last name?

2024-04-09 16:37 UTC, rickaw requested changes

2024-04-10 09:37 UTC, minalui commented on supabase/migrations/20240409100702_add_profile_plus_view.sql
> +     LEFT JOIN auth.users ON ((profiles.primary_key = users.id)))
Yep 💯

2024-04-11 12:05 UTC, rickaw commented on src/app/clients/getClientsData.ts
> +            const logId = await logInfoReturnLogId("Aborted fetch: client table", clientError);
(same in other places please)
```suggestion
            const logId = await logInfoReturnLogId("Aborted fetch: client table", { error: clientError });
```

2024-04-11 12:05 UTC, rickaw commented on src/app/clients/getClientsData.ts
> +    }
```suggestion
    const{ data: clientCount, error: clientCountError } = await getClientsCount(supabase, filters, abortSignal);
    if (clientCountError) {
        return { data: null, error: clientCountError };
    }
```

2024-04-11 12:05 UTC, rickaw commented on src/app/clients/getClientsData.ts
> +    console.log("here");
```suggestion
```

2024-04-11 12:05 UTC, rickaw commented on src/common/fetch.ts
> +        void logErrorReturnLogId("Failed to fetch: user profile", error);
```suggestion
        void logErrorReturnLogId("Failed to fetch: user profile", { error });
```

2024-04-11 14:36 UTC, minalui commented on src/app/admin/usersTable/UsersTable.tsx
> +                    ${error.logId}`);
Yes forgot this!

2024-04-12 13:19 UTC, rickaw approved these changes

2024-04-12 13:32 UTC, merged