Vfb 192 add audit logs when an invite link is sent
NorwoodAndBrixtonFoodbank/nbf-website pull request #252
Opened 2024-04-10 12:25 UTC by minalui

## What's changed
- Add audit logs for when email invite is sent and when profile for user is created
- Add profile_id to audit log for new user_id

## Screenshots / Videos
| Before     | After      |
|------------|------------|
| paste_here | paste_here |

## Checklist
- [x] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [x] I have documented the testing steps for QA
- [ ] I have self-reviewed this PR
- [x] Make sure you've verified it works via `npm run dev`
- [x] Make sure you've verified it works via `npm run build` and `npm run start`
- [x] Make sure you've fixed all linting problems with `npm run lint_fix`
- [x] Make sure you've tested via `npm run test:e2e`

If you have made any changes to the database...
  - [x] The migration files are up-to-date with my final set up (`npx supabase db diff -f <name_of_migration>` should create nothing at this point)
  - [x] I have updated the typescript definitions for the database with `db:local:generate_types`
  - [x] I have modified the seed in `supabase/seed/seed.mts` if appropriate
  - [x] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed` 
  - [x] With my final set up, I can run `npm run dev:reset_supabase` without any errors.
  - Does this require resetting the deployed database? - YES / NO (remove as appropriate)
  - [x] I have checked that migration can happen successfully without resetting the database, doing the following.
    - Make sure you have rebased your branch onto dev or merged dev into your branch.
    - Checkout the dev branch
    - Run `npm run post_checkout` to reset the database, including the seed data.
    - Checkout your branch
    - Run `npx supabase migrations up --include-all --local` to run all outstanding migration files
    - Check that the resulting database is what you expect, bar any seed data changes.

2024-04-10 13:40 UTC, rickaw commented on supabase/seed.sql
Have changed the seed at all? Could you check if this change is needed?

2024-04-10 14:17 UTC, minalui commented on supabase/seed.sql
Not needed and deleted 👍

2024-04-10 14:38 UTC, rickaw requested changes

2024-04-10 14:38 UTC, rickaw commented on supabase/seed.sql
Seems like the seed.sql is deleted now...

2024-04-10 14:38 UTC, rickaw commented on src/server/adminInviteUser.ts
> +        const auditLog = {
I'm not comfortable that we have multiple consts with the name `auditLog` in this function. Can we rename them so we have a clear distinction between them?

2024-04-10 14:38 UTC, rickaw commented on src/server/adminInviteUser.ts
> +    if (data) {
can we rename `data` here so we know what data that is? since this function is semi-long and does a few things

2024-04-10 14:38 UTC, rickaw commented on src/server/adminInviteUser.ts
> +            const logId = await logErrorReturnLogId("failed to create profile for user", {
```suggestion
            const logId = await logErrorReturnLogId(`failed to create profile for user with id ${data.user_id}`, {
```

2024-04-10 14:47 UTC, rickaw commented on supabase/seed.sql
I think what you meant to do was to remove all the changes you've made in seed.sql, not to delete the file

2024-04-11 12:11 UTC, rickaw requested changes

2024-04-11 12:11 UTC, rickaw commented on src/server/adminInviteUser.ts
> +    if (newUserData) {
is this if statement redundant since we check for errors and return above?

2024-04-11 12:11 UTC, rickaw commented on src/server/adminInviteUser.ts
> +    const { data: newUserData, error } = await adminAuthClient.inviteUserByEmail(
```suggestion
    const { data: newUserData, error: inviteUserError } = await adminAuthClient.inviteUserByEmail(
```

2024-04-11 12:11 UTC, rickaw commented on src/server/adminInviteUser.ts
> +                email: userDetails.email,
can we add the user ID in the content too?

2024-04-12 08:48 UTC, merged