VFB-81: Concurrent record editing
NorwoodAndBrixtonFoodbank/nbf-website pull request #291
Opened 2024-04-23 16:28 UTC by minalui

## What's changed
- Add last_updated column to parcels and clients table, default set to current utc
- Existing rows will have last_update set to utc when migration happens
- Add function to updated last_updated to current utc when an update is made to the row
- Change update functions to check last_updated in client side is the same as database
- Handle and display errors

## Screenshots / Videos
| Before     | After      |
|------------|------------|
| paste_here | paste_here |

## Checklist
- [x] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [x] I have documented the testing steps for QA
- [ ] I have self-reviewed this PR
- [x] Make sure you've verified it works via `npm run dev`
- [x] Make sure you've verified it works via `npm run build` and `npm run start`
- [x] Make sure you've fixed all linting problems with `npm run lint_fix`
- [x] Make sure you've tested via `npm run test:e2e`

If you have made any changes to the database...
  - [x] The migration files are up-to-date with my final set up (`npx supabase db diff -f <name_of_migration>` should create nothing at this point)
  - [x] I have updated the typescript definitions for the database with `db:local:generate_types`
  - [ ] I have modified the seed in `supabase/seed/seed.mts` if appropriate N/A
  - [ ] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed`  N/A
  - [ ] With my final set up, I can run `npm run dev:reset_supabase` without any errors. N/A
  - Does this require resetting the deployed database? - NO (remove as appropriate)
  - [x] I have checked that migration can happen successfully without resetting the database, doing the following.
    - Make sure you have rebased your branch onto dev or merged dev into your branch.
    - Checkout the dev branch
    - Run `npm run post_checkout` to reset the database, including the seed data.
    - Checkout your branch
    - Run `npx supabase migrations up --include-all --local` to run all outstanding migration files
    - Check that the resulting database is what you expect, bar any seed data changes.

2024-04-24 13:28 UTC, rickaw requested changes

2024-04-24 13:28 UTC, rickaw commented on src/app/clients/form/submitFormHelpers.ts
> +type addClientReturnType =
For convention, we'll stick to `...Result` :)
```suggestion
type addClientResult =
```

2024-04-24 13:28 UTC, rickaw commented on src/app/clients/form/submitFormHelpers.ts
> +type editClientReturnType =
```suggestion
type editClientResult =
```

2024-04-24 14:59 UTC, minalui commented on supabase/migrations/20240423141258_update_client_function_change.sql
The function now only updates a row if primary_key and last_updated matches. It also returns the client ID and number of rows updated in a new database type.

2024-04-25 08:45 UTC, minalui commented on src/app/error.tsx
OK!

2024-04-25 09:17 UTC, rickaw approved these changes
one last thing but feel free to merge once that's addressed!

2024-04-25 09:17 UTC, rickaw commented on src/app/clients/ClientsPage.tsx
> +    }, [startPoint, endPoint, primaryFilters, sortState, fetchAndDisplayClientsData]);
I don't think you need this change anymore since we don't call fetchAndDisplayClientsData?

2024-04-25 09:30 UTC, rickaw commented on src/app/clients/ClientsPage.tsx
> +    }, [startPoint, endPoint, primaryFilters, sortState, fetchAndDisplayClientsData]);
ah that makes sense!

2024-04-25 09:37 UTC, merged