#232: Use en-GB locale for calendar
NorwoodAndBrixtonFoodbank/nbf-website pull request #313
Opened 2024-05-02 10:18 UTC by maxjohns0n

## What's changed
Set the calendar to use en-GB locale so that the date is formatted correctly (day/month). This also makes Monday the first day of the week (which I imagine is a good thing?).

## Screenshots / Videos
| Before     | After      |
|------------|------------|
| ![image](https://private-user-images.githubusercontent.com/80202270/319672080-f42f37c8-79fb-4adf-99c8-e310d1a4d99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDQ3NDYsIm5iZiI6MTcxNDY0NDQ0NiwicGF0aCI6Ii84MDIwMjI3MC8zMTk2NzIwODAtZjQyZjM3YzgtNzlmYi00YWRmLTk5YzgtZTMxMGQxYTRkOTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEwMDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDNlZjFjZDNmZWNkMTc0MzE3Nzk1YTA2ZTlmZmQzMDBkMGRhNjg1ZDNkZGEwZTJkMDVmZjJmMDIzOWQyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G7aMek82wLvaB399u3sIW8uEB2AKboK5BDqtzRtDpMU) | ![image](https://github.com/NorwoodAndBrixtonFoodbank/nbf-website/assets/167985147/6bff3e2a-67b3-433c-a79f-f697d03a84bd) |

## Checklist
- [ ] The ticket is up-to-date - Please document any deviations from the original approach if there is any.
- [ ] I have documented the testing steps for QA
- [ ] I have self-reviewed this PR
- [ ] Make sure you've verified it works via `npm run dev`
- [ ] Make sure you've verified it works via `npm run build` and `npm run start`
- [ ] Make sure you've fixed all linting problems with `npm run lint_fix`
- [ ] Make sure you've tested via `npm run test:e2e`

If you have made any changes to the database...
  - [ ] The migration files are up-to-date with my final set up (`npx supabase db diff -f <name_of_migration>` should create nothing at this point)
  - [ ] I have updated the typescript definitions for the database with `db:local:generate_types`
  - [ ] I have modified the seed in `supabase/seed/seed.mts` if appropriate
  - [ ] If I have modified the seed, I have also generated the seed with `npm run db:generate_seed` 
  - [ ] With my final set up, I can run `npm run dev:reset_supabase` without any errors.
  - Does this require resetting the deployed database? - YES / NO (remove as appropriate)
  - [ ] I have checked that migration can happen successfully without resetting the database, doing the following.
    - Make sure you have rebased your branch onto dev or merged dev into your branch.
    - Checkout the dev branch
    - Run `npm run post_checkout` to reset the database, including the seed data.
    - Checkout your branch
    - Run `npx supabase migrations up --include-all --local` to run all outstanding migration files
    - Check that the resulting database is what you expect, bar any seed data changes.

2024-05-02 11:23 UTC, maxjohns0n commented
Changing the locale also means Monday is the first day of the week, and all times are in 24h instead of 12h. Is this what we want? It is consistent with how times are displayed elsewhere (e.g. audit logs).

2024-05-02 13:21 UTC, AmeliaIsCoding requested changes
Nice, but I think maybe we should stick with displaying 12 hour times. Is there a way to get both the date as DD/MM and the time as 12 hours? Maybe in the `views` prop there is some config we could use that allows this?

2024-05-02 13:48 UTC, maxjohns0n commented
> Nice, but I think maybe we should stick with displaying 12 hour times. Is there a way to get both the date as DD/MM and the time as 12 hours? Maybe in the `views` prop there is some config we could use that allows this?

Ok yes I found a way to keep all the times as they were before!

2024-05-03 09:40 UTC, AmeliaIsCoding approved these changes
Great! I like that now we only specify eventTimeFormat once :)

2024-05-03 09:55 UTC, minalui approved these changes
Looks great :)

2024-05-03 10:15 UTC, merged